### ISSUE TITLE
借仓库说一下 Quicker 相关问题

### ISSUE THREAD

**Issue by wuyudi** [Zacharia2/SuperMemo18-ON-Wine#3]
我也试过用 wine 安装 Quicker

32 位的 arch，需要 .Net 4.7.2, winetricks 正好有。我就安装了，winetricks 会一路安装各个版本的 dotnet 运行时。

然后 Quicker 的运行效果是这样的。能跑，但不完全能跑。

![image](https://user-images.githubusercontent.com/30024051/186479969-11e08ff0-5ad5-42fe-a9b0-c40b03d91bea.png)

log

```cs
0108:err:ole:CoGetContextToken apartment not initialised
log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />
0108:fixme:ole:thread_context_callback_ContextCallback 01935DB4, 01ECEF00, 04D1FB44, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 00000000
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E850, 00CEF368, 0021E854, 0021E848
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E850, 00CEF368, 0021E854, 0021E848
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E850, 00CEF368, 0021E854, 0021E848
2022-08-25 01:02:39,122 INFO Quicker.App -         =============  Started Logging  =============        
2022-08-25 01:02:39,129 INFO Quicker.App - Quicker:1.34.26.0  Windows:Microsoft Windows NT 6.1.7601 Service Pack 1
0024:fixme:combase:RoGetActivationFactory (L"Windows.ApplicationModel.DesignMode", {2c3893cc-f81a-4e7a-b857-76a80887e185}, 0021C170): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.ApplicationModel.DesignMode"
0024:fixme:combase:RoGetActivationFactory (L"Windows.ApplicationModel.DesignMode", {2c3893cc-f81a-4e7a-b857-76a80887e185}, 0021C170): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.ApplicationModel.DesignMode"
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
0124:fixme:netprofm:netprofm_cf_QueryInterface interface {b196b28f-bab4-101a-b69c-00aa00341d07} not implemented
006c:fixme:nsi:ipv6_forward_enumerate_all not implemented
012c:fixme:d3d:wined3d_check_device_format_conversion output 00D6B378, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
0108:fixme:ole:thread_context_callback_ContextCallback 01935DB4, 01ECEF00, 04D1FB44, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 00000000
2022-08-25 01:02:40,788 ERROR Quicker.App - 遇到了未捕获的异常。Exception from HRESULT: 0x88980406
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.NotifySyncModeStatus(Int32 enabledResult)
   at System.Windows.Media.MediaContext.NotifyChannelMessage()
   at System.Windows.Media.MediaContextNotificationWindow.MessageFilter(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-08-25 01:02:40,797 ERROR Quicker.App - Unhandled exception in Quicker v1.34.26.0
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.NotifySyncModeStatus(Int32 enabledResult)
   at System.Windows.Media.MediaContext.NotifyChannelMessage()
   at System.Windows.Media.MediaContextNotificationWindow.MessageFilter(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
0024:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 8
0024:fixme:wtsapi:WTSRegisterSessionNotification Stub 00010076 0x00000000
0024:fixme:msg:ChangeWindowMessageFilterEx 00010076 c033 1 0021DBF0
0024:fixme:msg:ChangeWindowMessageFilterEx 00010076 111 1 0021DBF0
2022-08-25 01:02:40,817 ERROR Quicker.App - 遇到了未捕获的异常。Exception from HRESULT: 0x88980406
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.OnWindowPosChanging(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
0024:err:seh:KiUserCallbackDispatcher ignoring exception
0164:fixme:console:default_ctrl_handler Terminating process 20 on event 0
```

所以我目前没解决。

**Comment by Zacharia2** [comment]
.net的微软Linux版本。https://docs.microsoft.com/en-us/dotnet/core/install/linux

 微软WebView2组件，当下的WebView2只支持Windows，但是微软承诺未来会支持MacOS和Linux。
或许可以使用wine安装它。

**Comment by Zacharia2** [comment]
pkgbuild 的权限问题，你可以把deb软件包解包后设置一下权限然后重新打包，应该就可以了。

**Comment by Zacharia2** [comment]
pkgbuild 的权限问题，你可以把deb软件包解包后设置一下权限然后重新打包，应该就可以了。

**Comment by Zacharia2** [comment]
我发布了新版的wine容器，它基于懒人包1.3.1，你可以尝试着用它构建PKGBUILD，依赖环境就是wine。如果想要更加方便打开的话需要创建desktop文件，在仓库嗯readme可以看到介绍。

**Comment by Zacharia2** [comment]
最近不怎么用Linux，因为Windows的软件包是我比较常用的在Linux中没有。Linux只有在虚拟机中使用，不过因为占用空间太大，所以只有打包软件的时候会用到。我喜欢使用mint Linux大薄荷发行版。简约清新。

**Comment by wuyudi** [comment]
> 最近不怎么用 Linux，因为 Windows 的软件包是我比较常用的在 Linux 中没有。Linux 只有在虚拟机中使用，不过因为占用空间太大，所以只有打包软件的时候会用到。我喜欢使用 mint Linux 大薄荷发行版。简约清新。

可以试试 [wslg](https://github.com/microsoft/wslg) (没用过)

**Comment by Zacharia2** [comment]
> > 最近不怎么用 Linux，因为 Windows 的软件包是我比较常用的在 Linux 中没有。Linux 只有在虚拟机中使用，不过因为占用空间太大，所以只有打包软件的时候会用到。我喜欢使用 mint Linux 大薄荷发行版。简约清新。
> 
> 可以试试 [wslg](https://github.com/microsoft/wslg) (没用过)

似乎只支持Windows11，现在没有升级的打算。

**Comment by Zacharia2** [comment]
@wuyudi 发布新版deb安装包了，可以试试看

**Comment by Zacharia2** [comment]
感觉可以打包一个quicker来用。

**Comment by Zacharia2** [comment]
不知道有没有现成的。
